# Generated by Django 5.0.6 on 2025-03-07 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardTitle', models.CharField(max_length=200)),
                ('cardDetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('depID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsSummary', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('depID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.department')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('depID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.department')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('teamID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('teamID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.team')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('cardID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.card')),
                ('engineID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.engineer')),
                ('teamLeadID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.teamleader')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsSummary', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('teamID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.team')),
            ],
        ),
    ]
