# Generated by Django 5.0.6 on 2025-04-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyhealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('ENGINEER', 'Engineer'), ('TEAM_LEADER', 'Team Leader'), ('DEPARTMENT_LEADER', 'Department Leader'), ('SENIOR_MANAGER', 'Senior Manager')], max_length=20)),
                ('depID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.department')),
                ('teamID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='departmentleader',
            name='depID',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='teamID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='engineID',
        ),
        migrations.DeleteModel(
            name='SeniorManager',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='teamID',
        ),
        migrations.RemoveField(
            model_name='review',
            name='teamLeadID',
        ),
        migrations.AddField(
            model_name='review',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.user'),
        ),
        migrations.DeleteModel(
            name='DepartmentLeader',
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.DeleteModel(
            name='TeamLeader',
        ),
    ]
