# Generated by Django 5.0.6 on 2025-04-16 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyhealth', '0002_user_remove_departmentleader_depid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ENGINEER', 'Engineer'), ('TEAM_LEADER', 'Team Leader'), ('DEPARTMENT_LEADER', 'Department Leader'), ('SENIOR_MANAGER', 'Senior Manager')], max_length=20)),
                ('depID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.department')),
                ('teamID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skyhealth.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
