# Generated by Django 5.0.6 on 2025-04-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyhealth', '0003_profile_alter_review_userid_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ENGINEER', 'Engineer'), ('TEAM_LEADER', 'Team Leader'), ('DEPARTMENT_LEADER', 'Department Leader'), ('SENIOR_MANAGER', 'Senior Manager'), ('SERVER_ADMIN', 'Server Admin')], max_length=20),
        ),
    ]
